### ISSUE TITLE
Stage's position in workflow client template

### ISSUE THREAD

**Issue by onca-vega** [tecnocen-com/yii2-workflow#1]
Actually I need a way to know where I'm going to display every stage in client template.
I'm handling this issue as a game table, so I have an array that tell's me where to put an stage or not, something like this:
var a = [
 ["apeeeeeeee"],
 ["peeeeeeeee"],
 ["eeeeeeeeee"],
 ["eeeeeeeeee"],
 ["eeeeeeeeee"]
];
Where "a" means an active or existent stage, let's say stage A, "p" means a probably stage, as the user wants to create it, and "e" means an empty space.
So for mapping this I need a way to save that stage A is going to be placed in [0][0] or [1][2] of this table, as this is an X and a Y integer value.

**Comment by Faryshta** [comment]
https://github.com/tecnocen-com/yii2-workflow/commit/3c743c1e4aaad71419f35bac0dfd5c6cfca6bee2 solves your issue?

**Comment by onca-vega** [comment]
yes, while I can patch or post with those attributes for sure.
